---
- name: check path exists
  stat:
    path: "{{ item.value }}"
  with_dict: "{{ java_all_log_path }}"
  register: pathvar_java

- name: set init list
  set_fact:
    java_log_path_list: []

- name: Gerneric java Log list
  set_fact:
    java_log_path_list: "{{ java_log_path_list + [ item.item ] }}"
  when:
    - item.stat.exists
  with_items: "{{ pathvar_java.results }}"

- debug:
    msg: "{{ java_log_path_list }}"

- name: Checks java logs path.
  shell: ls {{ item.value }}
  register: java_logs
  with_items: "{{ java_log_path_list }}"
  ignore_errors: yes

# - name: Write result of log_check to localfile.
#   copy:
#     content: "{{ java_logs.results }}"
#     dest: "/Users/ark/Documents/Kingbay/elk-oce/result/java_{{ ansible_default_ipv4.address }}.json"
#   when:
#     - java_logs is defined
#   become: false
#   delegate_to: 127.0.0.1